### ISSUE TITLE
EPERM issue with pesy@next

### ISSUE THREAD

**Issue by DrYSG** [esy/pesy#110]
On windows 10, using pesy@0.5.0-alpha.11 I get: 
```
{ Error: EPERM: operation not permitted, rename 'bin/__PACKAGE_NAME_UPPER_CAMEL__App.re' -> 'bin/MorphGraphqlServerApp.re'    at Object.renameSync (fs.js:589:3)
    at C:\Users\ysg4206\AppData\Roaming\npm\node_modules\pesy\src\Pesy.bs.js:169:13
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'bin/__PACKAGE_NAME_UPPER_CAMEL__App.re',
  dest: 'bin/MorphGraphqlServerApp.re' }

```
I am running in an admin console

**Comment by DrYSG** [comment]
Manas (prometheansacrifice) on discord :  suggested re-trying and this time the pesy command worked:
```
D:\CRIME\morph-graphql-server>pesy --template=reason-native-web/morph-graphql-server-pesy-template
Running esy pesy and building project dependencies -
Running esy pesy and building project dependencies \

```
Go figure. However, the install failed:

```
D:\CRIME\morph-graphql-server>esy install
info install 0.6.2 (using package.json)
.... fetching @opam/httpaf-lwt@github:anmonteiro/httpaf:httpaf-lwt.opam#76b461bed081c64908fb1fdfa076ab2c936ca62
.... fetching @opam/httpaf-lwt-unix@github:anmonteiro/httpaf:httpaf-lwt-unix.opam#76b461bed081c64908fb1fdfa076a
.... fetching @reason-native/rely@3.1.0esy: internal error, uncaught exception:
     Unix.Unix_error(Unix.EACCES, "rename", "D:\\CRIME\\morph-graphql-server\\_esy\\default\\tmp\\esy-53e7c5")
     Raised at file "src/core/lwt.ml", line 2999, characters 20-29
     Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
     Called from file "esy-lib/Cli.re", line 263, characters 9-28
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 25, characters 27-34
     Called from file "cmdliner.ml", line 116, characters 32-39
``

Not sure if this is a esy, pesy, or morph issue.

**Comment by ulrikstrid** [comment]
I can test this on my end, I just need to finish my current PR to morph and update the graphql template with the latest changes first.

**Comment by ManasJayanth** [comment]
The bootstrapper has been improved recently to rely less (almost none) no rename operations. Closing this for now, but feel free to re-open this
